    <footer>
      <div class="container">
	  
        <div class="row" style="margin-bottom:40px !important;">
          <div class="col-md-12">
			<div class="col-sm-8">
				<h2>À propos d'Advataxes</h2>
				<p>Advataxes est un logiciel comptable en ligne sur les dépenses des employés qui assiste votre organisation dans la gestion de la TPS/TVH, TVQ  pour les petites, moyennes et grandes entreprises. 
				Les employés peuvent compléter un compte de dépense de n'importe où avec un PC, une tablette ou un téléphone intelligent. 
				Ce logiciel est disponible en français et en anglais. 
				Advataxes est un produit d'<a href="http://www.advalorem.ca"></a>Ad Valorem qui est membre d'Antea qui est une association internationale de firmes independante.
				</p>
</div>
			<div class="col-sm-4" style="margin-top:20px;">
				<a class="btn btn-lg btn-primary" href="/fr/obtenez-un-mois-gratuit.aspx">Essayer Advataxes</a>
			</div>
          </div>
        </div>
	
		<div class="clear"></div>

        <div class="row">
		
			<div class="col-md-12">
				<div class="col-sm-3">
					<b>Produit</b>
					<ul>
						<li><a href="/fr/simulation.aspx">Simulation</a></li>
						<li><a href="/fr/productivite.aspx">Productivité</a></li>
						<li><a href="/fr/parametres.aspx">Paramètres</a></li>
						<li><a href="/fr/comptabilite-et-gestion.aspx">Comptabilité et gestion</a></li>
						<li><a href="/fr/calculatrice-des-taxes-depenses-voyages.aspx">Calculatrice des taxes sur les dépenses de voyage</a></li>
						<li><a href="/fr/politique-de-confidentialite.aspx">Politique de confidentialité</a></li>
						<li><a href="/fr/conditions-utilisation.aspx">Conditions d'utilisation</a></li>
					</ul>					
				</div>
				<div class="col-sm-3">
					<b>Information</b>
					<ul>
						<li><a href="/fr/index.aspx#page-features">Contenu</a></li>
						<li><a href="/fr/index.aspx#page-pricing">Prix</a></li>
						<li><a href="https://blog.advataxes.ca/fr/">Blogue</a></li>
					</ul>					
				</div>
				<div class="col-sm-3">
					<b>Service</b>
					<ul>
						<li><a href="/fr/demo.aspx">Demandez une démonstration</a></li>
						<li><a href="/fr/obtenez-un-mois-gratuit.aspx">Demandez un essai</a></li>
						<li><a href="/fr/exigences.aspx">Exigences</a></li>
						<li><a href="/Login.aspx">Connexion</a></li>
						<li><a href="/mobile/mlogin.aspx">Mobile</a></li>
						<li><a href="/fr/nous-contacter.aspx">Nous contacter</a></li>
					</ul>					
				</div>

				<div class="col-sm-3">
					<b>Social</b>
					<ul class="footerSocialList">
						<li><a href="https://www.facebook.com/Advataxes"><img class="footerSocial" src="/en/images/social-facebook.png" /></a></li>
						<li><script src="//platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script><script type="IN/FollowCompany" data-id="2285438" data-counter="none"></script></li>
						<li><a href="https://twitter.com/AdValoremSerge"><img class="footerSocial" src="/en/images/social-twitter.png" /></a></li>
						<li><a href="http://www.slideshare.net/Nexus987"><img class="footerSocial" src="/en/images/social-slideshare.png" /></a></li>
					</ul>
          <br />
          <b>Membre de</b>

          <li>
            <a href="https://advalorem.ca">
              <img class="" src="/en/images/logo-advalorem-en-tm-280x73.png" />
            </a>
          </li>
          <li>
            <a href="http://www.antea-int.com/">
              <img class="" src="/en/images/logo_antea.png" />
            </a>
          </li>

        </div>

			</div>
		
			<div class="col-md-12 center">
				<p style="margin-top:15px;">&copy; Copyright <% Response.Write( Year(Date.Now).ToString ) %>. Ad Valorem Inc.</p>
			</div>

        </div><!-- end row fluid -->
      </div><!-- end container -->
    </footer>
