    <div class="navbar navbar-inverse navbar-fixed-top" id="navbar">
      <div class="navbar-inner">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
              <a href="#none" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="fa fa-bars"></span>
                <span class="btn-navbar-text">Menu</span>
              </a>
              
              <a class="brand" href="/fr/index.aspx"><span class="logo"></span></a>
              
              <div class="navbar-collapse">
                <div class="nav-menu pull-left">
                  <ul class="nav nav-pills">
                    <li><a href="/fr/index.aspx#page-features">Contenu</a></li>
                    <li><a href="/fr/index.aspx#page-pricing">Prix</a></li>
                    <li class="dropdown">
                      <a href="#none" class="dropdown-toggle" data-toggle="dropdown">Plus <b class="caret"></b></a>
                      <ul class="dropdown-menu">
						<li><a href="/fr/simulation.aspx">Simulation</a></li>
						<li><a href="/fr/productivite.aspx">Productivité</a></li>
						<li><a href="/fr/parametres.aspx">Paramètres fiscaux</a></li>
						<li><a href="/fr/comptabilite-et-gestion.aspx">Comptabilité et gestion</a></li>
						<li><a href="/fr/calculatrice-des-taxes-depenses-voyages.aspx">Calculatrice des taxes sur les dépenses de voyage</a></li>
						<li><a href="https://blog.advataxes.ca/fr/">Blogue</a></li>
                      </ul>
                    </li>
                  </ul>
                </div><!-- end nav-menu -->

				  <div class="nav-user pull-right">
                  <ul class="nav nav-user-options">
                    <li class="login"><a href="/mobile/mlogin.aspx" class="btn btn-primary">Mobile</a></li>
                    <li class="signup"><a href="/Login.aspx?lang=f" class="btn btn-primary">Connexion</a></li>
					<li class="signup"><a href="/en/index.aspx" class="language">English</a></li>
                  </ul>
                </div><!-- end nav-user -->
				
                </div><!-- end nav-menu -->

              </div><!-- end navbar-collapse -->
            </div><!-- end col-md-12 -->
          </div><!-- end row fluid -->
        </div><!-- end container -->
      </div><!-- end navbar-inner -->
    </div><!-- end navbar -->
