'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewReports

    '''<summary>
    '''lbl210 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl210 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboReportRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboReportRange As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl237 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl237 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboFinancialYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFinancialYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl244 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl244 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPeriod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl222 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl222 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboEmpReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEmpReports As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl215 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl215 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboReportType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboReportType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl73 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl73 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEmp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''llb43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents llb43 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboJur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboJur As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl60 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboOrgCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboOrgCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl545 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl545 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboGL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CT__D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CT__D As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDivision As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CT___P control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CT___P As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProject As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CT___C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CT___C As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCostCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCostCenter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CTW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CTW As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboWorkOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboWorkOrder As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExport As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hdnViewReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnViewReport As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnExportExcelText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnExportExcelText As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnOrgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnOrgID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAccSeg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccSeg As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnITR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnITR As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnITC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnITC As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnRITCON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRITCON As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnRITCBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRITCBC As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnRITCPEI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRITCPEI As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAccountPayable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccountPayable As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sqlFinalizedReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlFinalizedReports As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlEmployees As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlJurisdictions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlJurisdictions As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlOrgCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlOrgCategories As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlGetExpenseAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlGetExpenseAccounts As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDivisions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDivisions As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlFinalizedProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlFinalizedProjects As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlFinalizedWorkOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlFinalizedWorkOrders As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlFinalizedCostCenters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlFinalizedCostCenters As Global.System.Web.UI.WebControls.SqlDataSource
End Class
