'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MyReceipts

    '''<summary>
    '''hdnEmpID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEmpID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sqlDelegate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDelegate As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lbl377 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl377 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCreateFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCreateFor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl373 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl373 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboViewFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboViewFor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl420 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl420 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gridViewReceipts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridViewReceipts As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hdnCreateExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCreateExpense As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sqlUploads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlUploads As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''hdnPUK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPUK As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnOpenReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnOpenReport As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDelete As Global.System.Web.UI.WebControls.HiddenField
End Class
