    <footer>
      <div class="container">
	  
        <div class="row" style="margin-bottom:40px !important;">
          <div class="col-md-12">
			<div class="col-sm-8">
				<h2>About Advataxes</h2>
				<p>Advataxes is an online accounting software for employee expenses that automates recoverable GST/HST and QST for small, medium and large businesses. 
				Employees can fill out and submit their expense reports to their supervisors from anywhere using their PC, tablet or smartphone in no time. 
				This online software is available in English and French. 
				Advataxes is a product of <a href="http://www.advalorem.ca">Ad Valorem</a> which is a member of Antea an internationnal association of independent firms.</p>
</div>
			<div class="col-sm-4" style="margin-top:20px;">
				<a class="btn btn-lg btn-primary" href="/en/get-one-month-free.aspx">Try Advataxes Now</a>
			</div>
          </div>
        </div>
	
		<div class="clear"></div>

        <div class="row">
		
			<div class="col-md-12">
				<div class="col-sm-3">
					<b>Product</b>
					<ul>
						<li><a href="/en/simulation.aspx">Simulation</a></li>
						<li><a href="/en/productivity.aspx">Productivity</a></li>
						<li><a href="/en/parameters.aspx">Parameters</a></li>
						<li><a href="/en/accounting-and-management.aspx">Accounting & Management</a></li>
						<li><a href="/en/tax-calculator-for-travel-expenses.aspx">Tax Calculator for Travel Expenses</a></li>
						<li><a href="/en/privacy-policy.aspx">Privacy Policy</a></li>
						<li><a href="/en/terms-of-use.aspx">Terms of Use</a></li>
					</ul>					
				</div>
				<div class="col-sm-3">
					<b>General info</b>
					<ul>
						<li><a href="/#page-features">Features</a></li>
						<li><a href="/#page-pricing">Pricing</a></li>
						<li><a href="https://blog.advataxes.ca">Blog</a></li>
					</ul>					
				</div>
				<div class="col-sm-3">
					<b>Service</b>
					<ul>
						<li><a href="/en/demo.aspx">Demo Request</a></li>
						<li><a href="/en/get-one-month-free.aspx">Try Out Request</a></li>
						<li><a href="/en/requirements.aspx">Requirements</a></li>
						<li><a href="/Login.aspx">Log In</a></li>
						<li><a href="/mobile/mlogin.aspx">Mobile</a></li>
						<li><a href="/en/contact.aspx">Contact Us</a></li>
					</ul>					
				</div>

				<div class="col-sm-3">
					<b>Social</b>
					<ul class="footerSocialList">
						<li><a href="https://www.facebook.com/Advataxes"><img class="footerSocial" src="/en/images/social-facebook.png" /></a></li>
						<li><script src="//platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script><script type="IN/FollowCompany" data-id="2285438" data-counter="none"></script></li>
						<li><a href="https://twitter.com/AdValoremSerge"><img class="footerSocial" src="/en/images/social-twitter.png" /></a></li>
						<li><a href="http://www.slideshare.net/Nexus987"><img class="footerSocial" src="/en/images/social-slideshare.png" /></a></li>
					</ul>
          <br />
					<b>Member of</b>
          
						<li><a href="https://advalorem.ca"><img class="" src="/en/images/logo-advalorem-en-tm-280x73.png" /></a></li>
						<li><a href="http://www.antea-int.com/"><img class="" src="/en/images/logo_antea.png" /></a></li>
			
				</div>

			</div>
		
			<div class="col-md-12 center">
				<p style="margin-top:15px;">&copy; Copyright <% Response.Write( Year(Date.Now).ToString ) %>. Ad Valorem Inc.</p>
			</div>

        </div><!-- end row fluid -->
      </div><!-- end container -->
    </footer>
