'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Expenses
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AdvataxesResources.Expenses", GetType(Expenses).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expense was saved.
        '''</summary>
        Public Shared ReadOnly Property ConfirmExpenseSave() As String
            Get
                Return ResourceManager.GetString("ConfirmExpenseSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an error while uploading your file..
        '''</summary>
        Public Shared ReadOnly Property GenericErrorFileUpload() As String
            Get
                Return ResourceManager.GetString("GenericErrorFileUpload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The GST amount entered is higher than the total for this expense..
        '''</summary>
        Public Shared ReadOnly Property GSTPaidHigherThanAmount() As String
            Get
                Return ResourceManager.GetString("GSTPaidHigherThanAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The HST amount entered is higher than the total for this expense..
        '''</summary>
        Public Shared ReadOnly Property HSTPaidHigherThanAmount() As String
            Get
                Return ResourceManager.GetString("HSTPaidHigherThanAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The QST amount entered is higher than the total for this expense..
        '''</summary>
        Public Shared ReadOnly Property QSTPaidHigherThanAmount() As String
            Get
                Return ResourceManager.GetString("QSTPaidHigherThanAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The total of the taxes entered are higher than the total for this expense..
        '''</summary>
        Public Shared ReadOnly Property TaxesPaidHigherThanAmount() As String
            Get
                Return ResourceManager.GetString("TaxesPaidHigherThanAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File was not uploaded. File cannot be larger than 5MB.
        '''</summary>
        Public Shared ReadOnly Property UploadedFileIsTooLarge() As String
            Get
                Return ResourceManager.GetString("UploadedFileIsTooLarge", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
